The answer to *p2* produced by this code was not accepted as correct by AoC.
However, I really can't find my mistake, and it does produce the correct answer (and correct subresults) for the sample input.
So, I'm still committing it. :-)

Remark: on my system, using pypy3 7.3.10, this code runs in about 0.28 seconds, while in regular python 3.10.8 it takes more than 9 seconds!
